export const Industries = [
  'Agriculture',
  'Mining and Quarrying',
  'Manufacturing',
  'Construction',
  'Transportation and Warehousing',
  'Wholesale and Retail Trade',
  'Finance and Insurance',
  'Real Estate',
  'Professional, Scientific, and Technical Services',
  'Educational Services',
  'Health Care and Social Assistance',
  'Arts, Entertainment, and Recreation',
  'Accommodation and Food Services',
  'Other Services (except Public Administration)',
  'Information Technology (IT)',
  'Telecommunications',
  'Energy and Utilities                          ',
  'Aerospace and Defense',
  'Automotive',
  'Biotechnology and Pharmaceuticals',
  'Chemicals and Petrochemicals',
  'Electronics and Electrical ',
  'Environmental Services',
  'Food and Beverage',
  'Healthcare Technology',
  'Internet and E-commerce',
  'Logistics and Supply Chain',
  'Media and Advertising',
  'Nonprofit and Social Services',
];

export const Skills = ['UI/UX', 'Web developmnt'];
