export const Skills = [
  'Product Manager',
  'Web development',
  'Database management',
  'Networking',
  'Cloud computing',
  'Artificial Intelligence (AI)',
  'Mobile application development',
  'DevOps',
  'Project management',
  'Analytical and problem-solving',
  'Cybersecurity',
  'Data analysis and visualization',
  'Software development',
  'Business acumen',
  'Strategic thinking',
  'Collaboration and teamwork',
  'User experience (UX) design',
  'User interface (UI) design',
  'Graphic design',
  'Industrial design',
  'Product development',
  'Engineering',
  'Research and analysis',
  'Creative thinking',
  'Big Data Analytics',
  'Machine Learning',
  'Internet of Things (IoT)',
  'Virtual and Augmented Reality',
  'Blockchain',
  'Digital Marketing',
  'Data Science',
  'Quality Assurance and Testing',
  'Operating Systems and Servers',
  'System Administration',
  'Technical Writing',
  'Cloud Architecture',
];

export const YearsOfExp = [
  '1 year',
  '2 years',
  '3 years',
  '4 years',
  '5 to 9 years',
  '10 years+',
];

export const ExpertLevel = ['Beginner', 'Experienced', 'Advanced', 'Expert'];
